jobs:
- pysparkJob:
    jarFileUris:
    - gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar
    mainPythonFileUri: gs://secret-footing-366022/dataproc/bigquery_spark.py
  stepId: foo
placement:
  managedCluster:
    clusterName: ephemeral-cluster
    config:
      masterConfig:
        machineTypeUri: n1-standard-4
      workerConfig:
        machineTypeUri: n1-standard-4
        numInstances: 2
